// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "coindrop": erc721 Resource Client
//
// Command:
// $ goagen
// --design=github.com/waymobetta/go-coindrop-api/design
// --out=$(GOPATH)/src/github.com/waymobetta/go-coindrop-api
// --version=v1.4.1

package client

import (
	"bytes"
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// AssignErc721Path computes a request path to the assign action of erc721.
func AssignErc721Path() string {

	return fmt.Sprintf("/v1/internal/erc721/assign")
}

// Assign an ERC721 to a user
func (c *Client) AssignErc721(ctx context.Context, path string, payload *AssignERC721Payload, contentType string) (*http.Response, error) {
	req, err := c.NewAssignErc721Request(ctx, path, payload, contentType)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewAssignErc721Request create the request corresponding to the assign action endpoint of the erc721 resource.
func (c *Client) NewAssignErc721Request(ctx context.Context, path string, payload *AssignERC721Payload, contentType string) (*http.Request, error) {
	var body bytes.Buffer
	if contentType == "" {
		contentType = "*/*" // Use default encoder
	}
	err := c.Encoder.Encode(payload, &body, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	if contentType == "*/*" {
		header.Set("Content-Type", "application/json")
	} else {
		header.Set("Content-Type", contentType)
	}
	if c.JWTAuthSigner != nil {
		if err := c.JWTAuthSigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}
