// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "coindrop": task Resource Client
//
// Command:
// $ goagen
// --design=github.com/waymobetta/go-coindrop-api/design
// --out=$(GOPATH)/src/github.com/waymobetta/go-coindrop-api
// --version=v1.3.1

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// ShowTaskPath computes a request path to the show action of task.
func ShowTaskPath() string {

	return fmt.Sprintf("/v1/tasks")
}

// Get user task
func (c *Client) ShowTask(ctx context.Context, path string, userID *string) (*http.Response, error) {
	req, err := c.NewShowTaskRequest(ctx, path, userID)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewShowTaskRequest create the request corresponding to the show action endpoint of the task resource.
func (c *Client) NewShowTaskRequest(ctx context.Context, path string, userID *string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	values := u.Query()
	if userID != nil {
		values.Set("userId", *userID)
	}
	u.RawQuery = values.Encode()
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
