// Code generated by goagen v1.4.1, DO NOT EDIT.
//
// API "coindrop": transactions Resource Client
//
// Command:
// $ goagen
// --design=github.com/waymobetta/go-coindrop-api/design
// --out=$(GOPATH)/src/github.com/waymobetta/go-coindrop-api
// --version=v1.3.1

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// ListTransactionsPath computes a request path to the list action of transactions.
func ListTransactionsPath(userID string) string {
	param0 := userID

	return fmt.Sprintf("/v1/transactions/%s", param0)
}

// Get list of user transactions
func (c *Client) ListTransactions(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewListTransactionsRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewListTransactionsRequest create the request corresponding to the list action endpoint of the transactions resource.
func (c *Client) NewListTransactionsRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.JWTAuthSigner != nil {
		if err := c.JWTAuthSigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}
