consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  Standard_error:
    description: A standard error response (default view)
    example:
      code: 400
      message: Bad Request
    properties:
      code:
        description: A code that describes the error
        example: 400
        format: int64
        type: integer
      message:
        description: A message that describes the error
        example: Bad Request
        type: string
    required:
    - code
    - message
    title: 'Mediatype identifier: application/standard_error+json; view=default'
    type: object
  User:
    description: A user (default view)
    example:
      cognitoAuthUserId: Eaque facere voluptates consequatur nihil odit.
      id: 7547923669139885077
      name: Quae aut cumque consequatur.
      walletAddress: Velit hic illum veniam magni nam.
    properties:
      cognitoAuthUserId:
        description: Cognito auth user ID
        example: Eaque facere voluptates consequatur nihil odit.
        type: string
      id:
        description: Unique user ID
        example: 7547923669139885077
        format: int64
        type: integer
      name:
        description: Name of user
        example: Quae aut cumque consequatur.
        type: string
      walletAddress:
        description: Wallet address
        example: Velit hic illum veniam magni nam.
        type: string
    required:
    - id
    title: 'Mediatype identifier: application/vnd.user+json; view=default'
    type: object
  UserPayload:
    description: User payload
    example:
      cognitoAuthUserId: Iure amet.
    properties:
      cognitoAuthUserId:
        description: Cognito auth user ID
        example: Iure amet.
        type: string
    required:
    - cognitoAuthUserId
    title: UserPayload
    type: object
  Wallet:
    description: A wallet (default view)
    example:
      walletAddress: Unde aliquam voluptatibus ut.
    properties:
      walletAddress:
        description: wallet address
        example: Unde aliquam voluptatibus ut.
        type: string
    required:
    - walletAddress
    title: 'Mediatype identifier: application/vnd.wallet+json; view=default'
    type: object
host: localhost:5000
info:
  description: A simple goa service
  title: The Coindrop API
  version: ""
paths:
  /v1/users:
    post:
      description: Create a new user
      operationId: user#create
      parameters:
      - description: User payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/UserPayload'
      produces:
      - application/standard_error+json
      - application/vnd.user+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Standard_error'
        "404":
          description: Not Found
        "410":
          description: Gone
          schema:
            $ref: '#/definitions/Standard_error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Standard_error'
      schemes:
      - http
      summary: create user
      tags:
      - user
  /v1/users/{userID}:
    get:
      description: Get user by id
      operationId: user#show
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: integer
      produces:
      - application/vnd.user+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/User'
        "404":
          description: Not Found
      schemes:
      - http
      summary: show user
      tags:
      - user
  /v1/wallets:
    get:
      description: Get user wallet
      operationId: wallet#show
      parameters:
      - description: userID
        in: query
        name: userID
        required: false
        type: string
      produces:
      - application/standard_error+json
      - application/vnd.wallet+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Wallet'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/Standard_error'
      schemes:
      - http
      summary: show wallet
      tags:
      - wallet
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  NotFound:
    description: Not Found
  OK:
    description: OK
    schema:
      $ref: '#/definitions/User'
schemes:
- http
swagger: "2.0"
