consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  Quiz:
    description: Quiz (default view)
    example:
      quizObject: false
    properties:
      quizObject:
        description: Quiz object
        example: false
    required:
    - quizObject
    title: 'Mediatype identifier: application/vnd.quiz+json; view=default'
    type: object
  Results:
    description: Quiz results (default view)
    example:
      quizResultsList: "1973-10-26T23:57:41Z"
    properties:
      quizResultsList:
        description: quiz results list
        example: "1973-10-26T23:57:41Z"
    required:
    - quizResultsList
    title: 'Mediatype identifier: application/vnd.results+json; view=default'
    type: object
  Standard_error:
    description: A standard error response (default view)
    example:
      code: 400
      message: Bad Request
    properties:
      code:
        description: A code that describes the error
        example: 400
        format: int64
        type: integer
      message:
        description: A message that describes the error
        example: Bad Request
        type: string
    required:
    - code
    - message
    title: 'Mediatype identifier: application/standard_error+json; view=default'
    type: object
  TaskPayload:
    description: Task payload
    example:
      cognitoAuthUserId: Autem est.
      taskName: Omnis labore.
      taskState: Et non.
    properties:
      cognitoAuthUserId:
        description: Cognito auth user ID
        example: Autem est.
        type: string
      taskName:
        description: task name
        example: Omnis labore.
        type: string
      taskState:
        description: task state
        example: Et non.
        type: string
    required:
    - cognitoAuthUserId
    - taskName
    - taskState
    title: TaskPayload
    type: object
  Tasks:
    description: Tasks (default view)
    example:
      taskList: 348fa2ce-70ad-46c0-84d8-05b0a35b62b5
    properties:
      taskList:
        description: list of tasks
        example: 348fa2ce-70ad-46c0-84d8-05b0a35b62b5
    required:
    - taskList
    title: 'Mediatype identifier: application/vnd.tasks+json; view=default'
    type: object
  User:
    description: A user (default view)
    example:
      cognitoAuthUserId: Perferendis et quis ut unde.
      id: Voluptatibus ut.
      name: Iure amet.
      walletAddress: Non ut.
    properties:
      cognitoAuthUserId:
        description: Cognito auth user ID
        example: Perferendis et quis ut unde.
        type: string
      id:
        description: Unique user ID
        example: Voluptatibus ut.
        type: string
      name:
        description: Name of user
        example: Iure amet.
        type: string
      walletAddress:
        description: Wallet address
        example: Non ut.
        type: string
    required:
    - id
    title: 'Mediatype identifier: application/vnd.user+json; view=default'
    type: object
  UserPayload:
    description: User payload
    example:
      cognitoAuthUserId: Corporis aut ullam.
    properties:
      cognitoAuthUserId:
        description: Cognito auth user ID
        example: Corporis aut ullam.
        type: string
    required:
    - cognitoAuthUserId
    title: UserPayload
    type: object
  Wallet:
    description: A wallet (default view)
    example:
      walletAddress: Corrupti eum fugit eaque.
    properties:
      walletAddress:
        description: wallet address
        example: Corrupti eum fugit eaque.
        type: string
    required:
    - walletAddress
    title: 'Mediatype identifier: application/vnd.wallet+json; view=default'
    type: object
  WalletPayload:
    description: Wallet payload
    example:
      cognitoAuthUserId: Officiis odit vero eum.
      walletAddress: Quo rerum saepe adipisci error itaque velit.
    properties:
      cognitoAuthUserId:
        description: Cognito auth user ID
        example: Officiis odit vero eum.
        type: string
      walletAddress:
        description: Wallet address
        example: Quo rerum saepe adipisci error itaque velit.
        type: string
    required:
    - cognitoAuthUserId
    - walletAddress
    title: WalletPayload
    type: object
host: localhost:5000
info:
  description: A simple goa service
  title: The Coindrop API
  version: ""
paths:
  /v1/quiz:
    get:
      description: Get quiz
      operationId: quiz#show
      parameters:
      - description: Quiz title
        in: query
        name: quizTitle
        required: false
        type: string
      produces:
      - application/standard_error+json
      - application/vnd.quiz+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Quiz'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/Standard_error'
      schemes:
      - http
      summary: show quiz
      tags:
      - quiz
  /v1/quiz/results:
    get:
      description: Get quiz results
      operationId: results#show
      parameters:
      - description: User ID
        in: query
        name: userId
        pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$
        required: false
        type: string
      produces:
      - application/standard_error+json
      - application/vnd.results+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Results'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/Standard_error'
      schemes:
      - http
      summary: show results
      tags:
      - results
  /v1/tasks:
    get:
      description: Get user tasks
      operationId: tasks#show
      parameters:
      - description: User ID
        in: query
        name: userId
        pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$
        required: false
        type: string
      produces:
      - application/standard_error+json
      - application/vnd.tasks+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Tasks'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/Standard_error'
      schemes:
      - http
      summary: show tasks
      tags:
      - tasks
    post:
      description: Update user task state
      operationId: tasks#update
      parameters:
      - description: Task payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/TaskPayload'
      produces:
      - application/standard_error+json
      - text/plain
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Standard_error'
        "404":
          description: Not Found
        "410":
          description: Gone
          schema:
            $ref: '#/definitions/Standard_error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Standard_error'
      schemes:
      - http
      summary: update tasks
      tags:
      - tasks
  /v1/users:
    post:
      description: Create a new user
      operationId: user#create
      parameters:
      - description: User payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/UserPayload'
      produces:
      - application/standard_error+json
      - application/vnd.user+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Standard_error'
        "404":
          description: Not Found
        "410":
          description: Gone
          schema:
            $ref: '#/definitions/Standard_error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Standard_error'
      schemes:
      - http
      summary: create user
      tags:
      - user
  /v1/users/{userId}:
    get:
      description: Get user by id
      operationId: user#show
      parameters:
      - description: User ID
        in: path
        name: userId
        pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$
        required: true
        type: string
      produces:
      - application/vnd.user+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/User'
        "404":
          description: Not Found
      schemes:
      - http
      summary: show user
      tags:
      - user
  /v1/wallets:
    get:
      description: Get user wallet
      operationId: wallet#show
      parameters:
      - description: User ID
        in: query
        name: userId
        pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$
        required: false
        type: string
      produces:
      - application/standard_error+json
      - application/vnd.wallet+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Wallet'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/Standard_error'
      schemes:
      - http
      summary: show wallet
      tags:
      - wallet
    post:
      description: Update user wallet
      operationId: wallet#update
      parameters:
      - description: Wallet payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/WalletPayload'
      produces:
      - application/standard_error+json
      - text/plain
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Standard_error'
        "404":
          description: Not Found
        "410":
          description: Gone
          schema:
            $ref: '#/definitions/Standard_error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Standard_error'
      schemes:
      - http
      summary: update wallet
      tags:
      - wallet
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  NotFound:
    description: Not Found
  OK:
    description: OK
schemes:
- http
swagger: "2.0"
