package coindroprouter

import (
	"github.com/waymobetta/go-coindrop-api/coindropauth"
	"github.com/waymobetta/go-coindrop-api/coindrophandlers"
)

// Routes is a struct object containing a slice of Routes
type Routes []Route

var routes = Routes{
	Route{
		"UsersGet",
		"GET",
		"/api/v1/getusers",
		coindrophandlers.UsersGet,
	},
	Route{
		"UserRemove",
		"POST",
		"/api/v1/removeuser",
		coindrophandlers.UserRemove,
	},
	Route{
		"UserAdd",
		"POST",
		"/api/v1/adduser",
		coindrophandlers.UserAdd,
	},
	Route{
		"UserGet",
		"POST",
		"/api/v1/getuser",
		coindrophandlers.UserGet,
	},
	Route{
		"UpdateWallet",
		"POST",
		"/api/v1/updatewallet",
		coindrophandlers.WalletUpdate,
	},
	Route{
		"RedditUpdate",
		"POST",
		"/api/v1/updateredditinfo",
		coindrophandlers.RedditUpdate,
	},
	Route{
		"UpdateRedditVerificationCode",
		"POST",
		"/api/v1/updateredditverificationcode",
		coindrophandlers.UpdateRedditVerificationCode,
	},
	Route{
		"GenerateRedditVerificationCode",
		"POST",
		"/api/v1/generateredditverificationcode",
		coindrophandlers.GenerateRedditVerificationCode,
	},
	Route{
		"ValidateRedditVerificationCode",
		"POST",
		"/api/v1/validateredditverificationcode",
		coindrophandlers.ValidateRedditVerificationCode,
	},
	Route{
		"SignUp",
		"POST",
		"/api/v1/signup",
		coindropauth.SignUp,
	},
	Route{
		"SignIn",
		"POST",
		"/api/v1/signin",
		coindropauth.SignUp,
	},
	Route{
		"StackUserAdd",
		"POST",
		"/api/v1/addstackuser",
		coindrophandlers.StackUserAdd,
	},
	Route{
		"StackUserGet",
		"POST",
		"/api/v1/getstackuser",
		coindrophandlers.StackUserGet,
	},
	Route{
		"StackUserUpdate",
		"POST",
		"/api/v1/updatestackinfo",
		coindrophandlers.StackUserUpdate,
	},
	Route{
		"GenerateStackVerificationCode",
		"POST",
		"/api/v1/generatestackverificationcode",
		coindrophandlers.GenerateStackVerificationCode,
	},
	Route{
		"ValidateStackVerificationCode",
		"POST",
		"/api/v1/validatestackverificationcode",
		coindrophandlers.ValidateStackVerificationCode,
	},
}
